# Generated by Django 4.0.1 on 2022-01-10 02:16

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StatsTracker', '0003_alter_stats_draws'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stats',
            options={'verbose_name_plural': 'Feedback'},
        ),
        migrations.AddField(
            model_name='stats',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='stats',
            name='draws',
            field=models.IntegerField(),
        ),
    ]
