# Generated by Django 4.0.1 on 2022-01-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StatsTracker', '0004_alter_stats_options_stats_color_alter_stats_draws'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stats',
            options={'verbose_name_plural': 'Team Stats'},
        ),
        migrations.AddField(
            model_name='stats',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
